# Generated by Django 4.2 on 2024-05-04 15:56

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('intitule', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Matiere',
                'ordering': ['intitule'],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=30)),
                ('description1', models.CharField(max_length=255)),
                ('description2', models.CharField(default='description', max_length=255)),
                ('image', models.ImageField(default='image1.jpeg', upload_to='images/media/')),
                ('contenuText', ckeditor.fields.RichTextField()),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('text', 'TEXT'), ('video', 'VIDEO')], max_length=5)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matiere_cours', to='appWeb.matiere')),
            ],
            options={
                'db_table': 'Cours',
                'ordering': ['titre'],
            },
        ),
    ]
