# Generated by Django 4.2 on 2024-05-04 22:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='cours',
            name='contenuText',
            field=ckeditor.fields.RichTextField(default='contenu'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='image',
            field=models.ImageField(default='image1.jpeg', upload_to=''),
        ),
    ]
