# Generated by Django 4.2 on 2024-05-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0002_cours_slug_alter_cours_contenutext_alter_cours_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100),
        ),
    ]
