# Generated by Django 4.2 on 2024-05-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0003_alter_cours_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='extension',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='cours',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
