# Generated by Django 4.2 on 2024-05-05 07:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0004_cours_extension_alter_cours_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='contenuText',
            field=tinymce.models.HTMLField(default='contenu'),
        ),
    ]
