# Generated by Django 4.2 on 2024-05-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0006_remove_cours_extension_remove_cours_slug'),
    ]

    operations = [
    ]
