# Generated by Django 4.2 on 2024-05-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0007_auto_20240505_0955'),
    ]

    operations = [
    ]
