# Generated by Django 4.2 on 2024-05-05 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0008_auto_20240505_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='pdf',
            field=models.FileField(default='groupe3.pdf', upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='cours',
            name='image',
            field=models.ImageField(default='image1.jpeg', upload_to='images_upload'),
        ),
    ]
