# Generated by Django 4.2 on 2024-05-10 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0009_cours_pdf_alter_cours_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='video',
            field=models.FileField(default='video.mp4', upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
