# Generated by Django 4.2 on 2024-05-16 23:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0010_cours_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cours',
            name='pdf',
            field=models.FileField(default='groupe3.pdf', upload_to='pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
