# Generated by Django 4.2 on 2024-05-17 00:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0011_alter_cours_id_alter_cours_pdf_alter_matiere_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='contient_cours',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cours',
            name='pdf',
            field=models.FileField(default='fichier.pdf', upload_to='pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
