# Generated by Django 4.2 on 2024-05-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0012_matiere_contient_cours_alter_cours_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('texte', 'TEXTE'), ('video', 'VIDEO')], max_length=5),
        ),
    ]
