# Generated by Django 4.2 on 2024-05-25 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appWeb', '0014_alter_cours_description2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_trans', models.TextField(default='vide')),
                ('date_trans', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_trans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Transaction',
                'ordering': ['date_trans'],
            },
        ),
    ]
